/*
 * Copyright (C) 2022-2024, Xiaohua Semiconductor Co., Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_HC32_INTC_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_HC32_INTC_H_

// #if defined(HC32F460)
#include <zephyr/dt-bindings/interrupt-controller/hc32f460-intc.h>
// #else
// #error "unsupported chip"
// #endif

/* Ext ch0 */
#define HC32_EXTINT0_IRQ_NUM             INTC_IRQ_INT022
#define HC32_EXTINT0_IRQ_PRIO            INTC_IRQ_PRIO_DEFAULT
/* Ext ch1 */
#define HC32_EXTINT1_IRQ_NUM             INTC_IRQ_INT023
#define HC32_EXTINT1_IRQ_PRIO            INTC_IRQ_PRIO_DEFAULT
/* Ext ch2 */
#define HC32_EXTINT2_IRQ_NUM             INTC_IRQ_INT024
#define HC32_EXTINT2_IRQ_PRIO            INTC_IRQ_PRIO_DEFAULT
/* Ext ch3 */
#define HC32_EXTINT3_IRQ_NUM             INTC_IRQ_INT025
#define HC32_EXTINT3_IRQ_PRIO            INTC_IRQ_PRIO_DEFAULT
/* Ext ch4 */
#define HC32_EXTINT4_IRQ_NUM             INTC_IRQ_INT026
#define HC32_EXTINT4_IRQ_PRIO            INTC_IRQ_PRIO_DEFAULT
/* Ext ch5 */
#define HC32_EXTINT5_IRQ_NUM             INTC_IRQ_INT027
#define HC32_EXTINT5_IRQ_PRIO            INTC_IRQ_PRIO_DEFAULT
/* Ext ch6 */
#define HC32_EXTINT6_IRQ_NUM             INTC_IRQ_INT028
#define HC32_EXTINT6_IRQ_PRIO            INTC_IRQ_PRIO_DEFAULT
/* Ext ch7 */
#define HC32_EXTINT7_IRQ_NUM             INTC_IRQ_INT029
#define HC32_EXTINT7_IRQ_PRIO            INTC_IRQ_PRIO_DEFAULT
/* Ext ch8 */
#define HC32_EXTINT8_IRQ_NUM             INTC_IRQ_INT030
#define HC32_EXTINT8_IRQ_PRIO            INTC_IRQ_PRIO_DEFAULT
/* Ext ch9 */
#define HC32_EXTINT9_IRQ_NUM             INTC_IRQ_INT031
#define HC32_EXTINT9_IRQ_PRIO            INTC_IRQ_PRIO_DEFAULT
/* Ext ch10 */
#define HC32_EXTINT10_IRQ_NUM            INTC_IRQ_INT032
#define HC32_EXTINT10_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
/* Ext ch11 */
#define HC32_EXTINT11_IRQ_NUM            INTC_IRQ_INT033
#define HC32_EXTINT11_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
/* Ext ch12 */
#define HC32_EXTINT12_IRQ_NUM            INTC_IRQ_INT034
#define HC32_EXTINT12_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
/* Ext ch13 */
#define HC32_EXTINT13_IRQ_NUM            INTC_IRQ_INT035
#define HC32_EXTINT13_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
/* Ext ch14 */
#define HC32_EXTINT14_IRQ_NUM            INTC_IRQ_INT036
#define HC32_EXTINT14_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
/* Ext ch15 */
#define HC32_EXTINT15_IRQ_NUM            INTC_IRQ_INT037
#define HC32_EXTINT15_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT


/* DMA1 ch0 */
#define HC32_DMA1_CH0_IRQ_NUM            INTC_IRQ_INT038
#define HC32_DMA1_CH0_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
/* DMA1 ch1 */
#define HC32_DMA1_CH1_IRQ_NUM            INTC_IRQ_INT039
#define HC32_DMA1_CH1_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
/* DMA1 ch2 */
#define HC32_DMA1_CH2_IRQ_NUM            INTC_IRQ_INT040
#define HC32_DMA1_CH2_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
/* DMA1 ch3 */
#define HC32_DMA1_CH3_IRQ_NUM            INTC_IRQ_INT041
#define HC32_DMA1_CH3_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT

/* DMA2 ch0 */
#define HC32_DMA2_CH0_IRQ_NUM            INTC_IRQ_INT042
#define HC32_DMA2_CH0_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
/* DMA2 ch1 */
#define HC32_DMA2_CH1_IRQ_NUM            INTC_IRQ_INT043
#define HC32_DMA2_CH1_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
/* DMA2 ch2 */
#define HC32_DMA2_CH2_IRQ_NUM            INTC_IRQ_INT020
#define HC32_DMA2_CH2_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
/* DMA2 ch3 */
#define HC32_DMA2_CH3_IRQ_NUM            INTC_IRQ_INT021
#define HC32_DMA2_CH3_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT

#if defined(HC32_USING_UART1)
#define HC32_UART1_RXERR_IRQ_NUM         INTC_IRQ_INT012
#define HC32_UART1_RXERR_IRQ_PRIO        INTC_IRQ_PRIO_DEFAULT
#define HC32_UART1_RX_IRQ_NUM            INTC_IRQ_INT082
#define HC32_UART1_RX_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
#define HC32_UART1_TX_IRQ_NUM            INTC_IRQ_INT081
#define HC32_UART1_TX_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT

#if defined(HC32_UART1_RX_USING_DMA)
#define HC32_UART1_RXTO_IRQ_NUM          INTC_IRQ_INT013
#define HC32_UART1_RXTO_IRQ_PRIO         INTC_IRQ_PRIO_DEFAULT
#endif

#if defined(RT_USING_SERIAL_V1) && defined(HC32_UART1_TX_USING_DMA)
#define HC32_UART1_TX_CPLT_IRQ_NUM       INTC_IRQ_INT080
#define HC32_UART1_TX_CPLT_IRQ_PRIO      INTC_IRQ_PRIO_DEFAULT
#elif defined(RT_USING_SERIAL_V2)
#define HC32_UART1_TX_CPLT_IRQ_NUM       INTC_IRQ_INT080
#define HC32_UART1_TX_CPLT_IRQ_PRIO      INTC_IRQ_PRIO_DEFAULT
#endif
#endif /* HC32_USING_UART1 */

#if defined(HC32_USING_UART2)
#define HC32_UART2_RXERR_IRQ_NUM         INTC_IRQ_INT014
#define HC32_UART2_RXERR_IRQ_PRIO        INTC_IRQ_PRIO_DEFAULT
#define HC32_UART2_RX_IRQ_NUM            INTC_IRQ_INT085
#define HC32_UART2_RX_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
#define HC32_UART2_TX_IRQ_NUM            INTC_IRQ_INT084
#define HC32_UART2_TX_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT

#if defined(HC32_UART2_RX_USING_DMA)
#define HC32_UART2_RXTO_IRQ_NUM          INTC_IRQ_INT015
#define HC32_UART2_RXTO_IRQ_PRIO         INTC_IRQ_PRIO_DEFAULT
#endif

#if defined(RT_USING_SERIAL_V1) && defined(HC32_UART2_TX_USING_DMA)
#define HC32_UART2_TX_CPLT_IRQ_NUM       INTC_IRQ_INT083
#define HC32_UART2_TX_CPLT_IRQ_PRIO      INTC_IRQ_PRIO_DEFAULT
#elif defined(RT_USING_SERIAL_V2)
#define HC32_UART2_TX_CPLT_IRQ_NUM       INTC_IRQ_INT083
#define HC32_UART2_TX_CPLT_IRQ_PRIO      INTC_IRQ_PRIO_DEFAULT
#endif
#endif /* HC32_USING_UART2 */

#if defined(HC32_USING_UART3)
#define HC32_UART3_RXERR_IRQ_NUM         INTC_IRQ_INT016
#define HC32_UART3_RXERR_IRQ_PRIO        INTC_IRQ_PRIO_DEFAULT
#define HC32_UART3_RX_IRQ_NUM            INTC_IRQ_INT088
#define HC32_UART3_RX_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
#define HC32_UART3_TX_IRQ_NUM            INTC_IRQ_INT087
#define HC32_UART3_TX_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT

#if defined(HC32_UART3_RX_USING_DMA)
#define HC32_UART3_RXTO_IRQ_NUM          INTC_IRQ_INT017
#define HC32_UART3_RXTO_IRQ_PRIO         INTC_IRQ_PRIO_DEFAULT
#endif

#if defined(RT_USING_SERIAL_V1) && defined(HC32_UART3_TX_USING_DMA)
#define HC32_UART3_TX_CPLT_IRQ_NUM       INTC_IRQ_INT086
#define HC32_UART3_TX_CPLT_IRQ_PRIO      INTC_IRQ_PRIO_DEFAULT
#elif defined(RT_USING_SERIAL_V2)
#define HC32_UART3_TX_CPLT_IRQ_NUM       INTC_IRQ_INT086
#define HC32_UART3_TX_CPLT_IRQ_PRIO      INTC_IRQ_PRIO_DEFAULT
#endif
#endif /* HC32_USING_UART3 */

#if defined(HC32_USING_UART4)
#define HC32_UART4_RXERR_IRQ_NUM         INTC_IRQ_INT018
#define HC32_UART4_RXERR_IRQ_PRIO        INTC_IRQ_PRIO_DEFAULT
#define HC32_UART4_RX_IRQ_NUM            INTC_IRQ_INT091
#define HC32_UART4_RX_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
#define HC32_UART4_TX_IRQ_NUM            INTC_IRQ_INT090
#define HC32_UART4_TX_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT

#if defined(HC32_UART4_RX_USING_DMA)
#define HC32_UART4_RXTO_IRQ_NUM          INTC_IRQ_INT019
#define HC32_UART4_RXTO_IRQ_PRIO         INTC_IRQ_PRIO_DEFAULT
#endif

#if defined(RT_USING_SERIAL_V1) && defined(HC32_UART4_TX_USING_DMA)
#define HC32_UART4_TX_CPLT_IRQ_NUM       INTC_IRQ_INT089
#define HC32_UART4_TX_CPLT_IRQ_PRIO      INTC_IRQ_PRIO_DEFAULT
#elif defined(RT_USING_SERIAL_V2)
#define HC32_UART4_TX_CPLT_IRQ_NUM       INTC_IRQ_INT089
#define HC32_UART4_TX_CPLT_IRQ_PRIO      INTC_IRQ_PRIO_DEFAULT
#endif
#endif /* HC32_USING_UART4 */

#if defined(HC32_USING_SPI1)
#define HC32_SPI1_ERR_IRQ_NUM            INTC_IRQ_INT008
#define HC32_SPI1_ERR_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
#endif

#if defined(HC32_USING_SPI2)
#define HC32_SPI2_ERR_IRQ_NUM            INTC_IRQ_INT009
#define HC32_SPI2_ERR_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
#endif

#if defined(HC32_USING_SPI3)
#define HC32_SPI3_ERR_IRQ_NUM            INTC_IRQ_INT010
#define HC32_SPI3_ERR_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
#endif

#if defined(HC32_USING_SPI4)
#define HC32_SPI4_ERR_IRQ_NUM            INTC_IRQ_INT011
#define HC32_SPI4_ERR_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
#endif

#if defined(HC32_USING_CAN1)
#define HC32_CAN1_IRQ_NUM                INTC_IRQ_INT126
#define HC32_CAN1_IRQ_PRIO               INTC_IRQ_PRIO_DEFAULT
#endif /* HC32_USING_CAN1 */

#if defined(HC32_USING_SDIO1)
#define HC32_SDIO1_IRQ_NUM               INTC_IRQ_INT122
#define HC32_SDIO1_IRQ_PRIO              INTC_IRQ_PRIO_DEFAULT
#endif /* HC32_USING_SDIO1 */

#if defined(HC32_USING_SDIO2)
#define HC32_SDIO2_IRQ_NUM               INTC_IRQ_INT124
#define HC32_SDIO2_IRQ_PRIO              INTC_IRQ_PRIO_DEFAULT
#endif /* HC32_USING_SDIO2 */

#if defined(RT_USING_ALARM)
#define HC32_RTC_ALARM_IRQ_NUM           INTC_IRQ_INT044
#define HC32_RTC_ALARM_IRQ_PRIO          INTC_IRQ_PRIO_DEFAULT
#endif/* RT_USING_ALARM */

#if defined(HC32_USING_USBD) || defined(HC32_USING_USBH)
#define HC32_USB_GLB_IRQ_NUM             INTC_IRQ_INT003
#define HC32_USB_GLB_IRQ_PRIO            INTC_IRQ_PRIO_DEFAULT
#endif/* HC32_USING_USBD */

#if defined (HC32_USING_QSPI)
#define HC32_QSPI_ERR_IRQ_NUM            INTC_IRQ_INT004
#define HC32_QSPI_ERR_IRQ_PRIO           INTC_IRQ_PRIO_DEFAULT
#endif /* HC32_USING_QSPI */

#if defined(HC32_USING_PULSE_ENCODER_TMRA_1)
#define HC32_PULSE_ENCODER_TMRA_1_OVF_IRQ_NUM   INTC_IRQ_INT080
#define HC32_PULSE_ENCODER_TMRA_1_OVF_IRQ_PRIO  INTC_IRQ_PRIO_DEFAULT
#define HC32_PULSE_ENCODER_TMRA_1_UDF_IRQ_NUM   INTC_IRQ_INT081
#define HC32_PULSE_ENCODER_TMRA_1_UDF_IRQ_PRIO  INTC_IRQ_PRIO_DEFAULT
#endif/* HC32_USING_PULSE_ENCODER_TMRA_1 */

#if defined(HC32_USING_PULSE_ENCODER_TMR6_1)
#define HC32_PULSE_ENCODER_TMR6_1_OVF_IRQ_NUM   INTC_IRQ_INT050
#define HC32_PULSE_ENCODER_TMR6_1_OVF_IRQ_PRIO  INTC_IRQ_PRIO_DEFAULT
#define HC32_PULSE_ENCODER_TMR6_1_UDF_IRQ_NUM   INTC_IRQ_INT051
#define HC32_PULSE_ENCODER_TMR6_1_UDF_IRQ_PRIO  INTC_IRQ_PRIO_DEFAULT
#endif/* HC32_USING_PULSE_ENCODER_TMR6_1 */

#if defined(HC32_USING_TMR0_1A)
#define HC32_USING_TMR0_1A_IRQ_NUM       INTC_IRQ_INT046
#define HC32_USING_TMR0_1A_IRQ_PRIO      INTC_IRQ_PRIO_DEFAULT
#endif/* HC32_USING_TMR0_1A */
#if defined(HC32_USING_TMR0_1B)
#define HC32_USING_TMR0_1B_IRQ_NUM       INTC_IRQ_INT047
#define HC32_USING_TMR0_1B_IRQ_PRIO      INTC_IRQ_PRIO_DEFAULT
#endif/* HC32_USING_TMR0_1B */
#if defined(HC32_USING_TMR0_2A)
#define HC32_USING_TMR0_2A_IRQ_NUM       INTC_IRQ_INT048
#define HC32_USING_TMR0_2A_IRQ_PRIO      INTC_IRQ_PRIO_DEFAULT
#endif/* HC32_USING_TMR0_2A */
#if defined(HC32_USING_TMR0_2B)
#define HC32_USING_TMR0_2B_IRQ_NUM       INTC_IRQ_INT049
#define HC32_USING_TMR0_2B_IRQ_PRIO      INTC_IRQ_PRIO_DEFAULT
#endif/* HC32_USING_TMR0_2B */

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_HC32_INTC_H_ */
